package org.usfirst.frc4212.Robot;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
    public static SpeedController driveTrainSPL1;
    public static SpeedController driveTrainSPL2;
    public static SpeedController driveTrainSPR1;
    public static SpeedController driveTrainSPR2;
    
    public static RobotDrive driveTrainRD;
    public static AnalogGyro driveTrainGyro;
    
    public static PowerDistributionPanel driveTrainPDP;
    
    public static SpeedController ballPickupSpark;
    public static SpeedController ballShooterSpark;
    
    public static SpeedController lift1Spark;
    public static SpeedController lift2Spark;
    public static DigitalInput liftLS;
    
    public static SpeedController gearSpark;

    public static void init() {
        driveTrainSPL1 = new Spark(0);
        LiveWindow.addActuator("DriveTrain", "SP1", (Spark) driveTrainSPL1);
        
        driveTrainSPL2 = new Spark(1);
        LiveWindow.addActuator("DriveTrain", "SP2", (Spark) driveTrainSPL2);
        
        driveTrainSPR1 = new Spark(2);
        LiveWindow.addActuator("DriveTrain", "SP1", (Spark) driveTrainSPR1);
        
        driveTrainSPR2 = new Spark(3);
        LiveWindow.addActuator("DriveTrain", "SP2", (Spark) driveTrainSPR2);
        
        driveTrainRD = new RobotDrive(driveTrainSPL1, driveTrainSPL2, driveTrainSPR1, driveTrainSPR2);
        
        driveTrainRD.setSafetyEnabled(false);
        driveTrainRD.setExpiration(0.1);
        driveTrainRD.setSensitivity(0.5);
        driveTrainRD.setMaxOutput(1.0);

        driveTrainRD.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainRD.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveTrainGyro = new AnalogGyro(0);
        LiveWindow.addSensor("DriveTrain", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);
        driveTrainPDP = new PowerDistributionPanel(0);
        LiveWindow.addSensor("DriveTrain", "PDP", driveTrainPDP);
        
        //Gear Controllers
        gearSpark = new Spark(4);
        LiveWindow.addActuator("Arm", "Spark1", (Spark) gearSpark);
        
        //PNEUMATICS NEEDED
        
        //Ball Controllers
        ballPickupSpark = new Spark(5);
        LiveWindow.addActuator("Elevator", "Spark2", (Spark) ballPickupSpark);
        
        ballShooterSpark = new Spark(6);
        LiveWindow.addActuator("Pickup", "Spark3", (Spark) ballShooterSpark);
        
        //Lift Controllers
        lift1Spark = new Spark(7);
        LiveWindow.addActuator("Pickup", "Spark3", (Spark) lift1Spark);
        
        lift2Spark = new Spark(8);
        LiveWindow.addActuator("Pickup", "Spark3", (Spark) lift2Spark);
        
        liftLS = new DigitalInput(0);
        LiveWindow.addSensor("Pickup", "PickupLS", liftLS);
	}
}
